from typing import Protocol


class TokenizerProtocol(Protocol):
    def __init__(self, vocabulary: dict[str, int]) -> None: ...
    def encode(self, text: str) -> list[int]: ...
    def decode(self, token_ids: list[int]) -> str: ...
